# Block descent for optimizing group knockoffs

There are 2 ways for optimizing the group knockoff problem. This notebook tests the block update strategy where we update an entire block at once. Two concerns arise 

+ Which solver (MOSEK, Hypatia.jl, SCS, SDPT3, Convex.jl) should we use to solve each individual block?
+ How to maintain inequality constraints after updating a block? Can we use Woodbury?

In [1]:
using Revise
using Knockoffs
using BlockDiagonals
using LinearAlgebra
using Hypatia
using JuMP
using ToeplitzMatrices
using StatsBase
using CovarianceEstimation
using CSV, DataFrames
using Ipopt, NLopt, Convex
# ENV["COLUMNS"] = 240

#
# test problem
#
# p = 50
# m = 5
# group_sizes = [5 for i in 1:div(p, 5)] # each group has 5 variables
# groups = vcat([i*ones(g) for (i, g) in enumerate(group_sizes)]...) |> Vector{Int}
# x = randn(p, p)
# Σ = x'*x
# StatsBase.cov2cor!(Σ, std(Σ, dims=1))

# genomAD panel
datadir = "/Users/biona001/Benjamin_Folder/research/4th_project/group_knockoff_test_data"
covfile = CSV.read(joinpath(datadir, "CorG_2_127374341_128034347.txt"), DataFrame)
Σ = covfile |> Matrix{Float64}
Σ = 0.99Σ + 0.01I #ensure PSD
groups, group_reps = hc_partition_groups(Symmetric(Σ))

# test on smaller data
p = 100
m = 5
groups = repeat(1:div(p, 5), inner=5)
Σ = Σ[1:p, 1:p];

┌ Info: Precompiling Knockoffs [878bf26d-0c49-448a-9df5-b057c815d613]
└ @ Base loading.jl:1423


## Suboptimal SDP group knockoffs

In [2]:
@time Gsdp_subopt, _ = solve_s_group(
    Symmetric(Σ), 
    groups, 
    :sdp_subopt,
    m = m,          # number of knockoffs per variable to generate
    verbose=true);  # whether to print informative intermediate results

 57.516694 seconds (195.72 M allocations: 11.198 GiB, 3.56% gc time, 96.92% compilation time)


In [3]:
@time Gsdp_subopt_correct, _ = solve_s_group(
    Symmetric(Σ),
    groups,
    :sdp_subopt_correct,
    m = m,          # number of knockoffs per variable to generate
    verbose=true);  # whether to print informative intermediate results

 14.569853 seconds (1.39 M allocations: 319.052 MiB, 0.82% gc time, 2.69% compilation time)


In [4]:
sum(abs.(Gsdp_subopt)), sum(abs.(Gsdp_subopt_correct))

(2.7201241717409594, 2.7302836303132523)

## Block SDP

In [8]:
@time Gsdp, _ = solve_s_group(
    Symmetric(Σ),
    groups,
    :sdp_block,
    tol = 0.01,
    niter = 100,
    m = m,          # number of knockoffs per variable to generate
    verbose=true);  # whether to print informative intermediate results

Init obj = 235.2707932279639
Iter 1 δ = 0.7755682378196394, obj = 225.20116600274866
Iter 2 δ = 0.47574086669727134, obj = 220.34862640641828
Iter 3 δ = 0.16443242755363174, obj = 219.01049738871737
Iter 4 δ = 0.10657549657125265, obj = 218.43246195701397
Iter 5 δ = 0.1055097481865343, obj = 217.93460525572783
Iter 6 δ = 0.08457076455189916, obj = 217.60287955512032
Iter 7 δ = 0.04957691394682995, obj = 217.4145096166481
Iter 8 δ = 0.026086881200521606, obj = 217.31006275708793
Iter 9 δ = 0.029165120308050962, obj = 217.21785913681433
Iter 10 δ = 0.029796650990568496, obj = 217.14182519287027
Iter 11 δ = 0.02495381261236862, obj = 217.07799367729805
Iter 12 δ = 0.01692652620760915, obj = 217.034901711239
Iter 13 δ = 0.00781669948229069, obj = 217.00826829277213
 11.215528 seconds (4.83 M allocations: 478.372 MiB, 0.73% gc time)


In [9]:
eigmin(Gsdp), eigmin((m+1)/m*Σ - Gsdp)

(-1.834298391689202e-9, -9.998987484334977e-6)

In [10]:
sum(abs.(Gsdp))

20.800768356238827

## Block ME

In [16]:
@time Gme, _ = solve_s_group(
    Symmetric(Σ),
    groups,
    :maxent_block,
    tol = 0.01,
    niter = 100,
    m = m,          # number of knockoffs per variable to generate
    verbose=true);  # whether to print informative intermediate results

Init obj = 235.2707932279639
Iter 1 δ = 0.5847267674082222, obj = -2097.2565813450396
Iter 2 δ = 0.10213344737383401, obj = -2083.4893298965612
Iter 3 δ = 0.005498749251665325, obj = -2083.5472818794738
  6.920310 seconds (2.12 M allocations: 147.948 MiB, 0.22% gc time)


In [17]:
eigmin(Gme), eigmin((m+1)/m*Σ - Gme)

(0.0059999980055812085, 0.004392919776716409)

In [19]:
sum(abs.(Gme))

13.956606769245765

## Block MVR (using JuMP.jl)

In [60]:
function solve_group_MVR_single_block(
    Σ11::AbstractMatrix,
    A11::AbstractMatrix,
    A12::AbstractMatrix, 
    invD22::AbstractMatrix,
    m::Int,
    ub::AbstractMatrix; # this is upper bound, equals [A12 A13]*inv(A22-S2 A32; A23 A33-S3)*[A21; A31]
    )
    # needed constants
    invZ_Yt = invD22 * A12'
    Y_invZ_Yt = A12 * invZ_Yt
    # Build model via JuMP
    p = size(Σ11, 1)
    model = Model(() -> Hypatia.Optimizer())
    @variable(model, -1 ≤ S[1:p, 1:p] ≤ 1, Symmetric)
    # SDP constraints
    @constraint(model, S in PSDCone())
    @constraint(model, ub - S in PSDCone())
    # objective
    @objective(model, Min, 
#         m^2*tr(S)             # works
#         m^2*tr(inv(S))        # doesn't work
        m^2*tr(inv(S)) + tr(inv(A11-S-Y_invZ_Yt)) + tr(invZ_Yt*(A11-S-Y_invZ_Yt)*invZ_Yt')
    )
    # solve and return
    JuMP.optimize!(model)
    success = Knockoffs.check_model_solution(model)
    return JuMP.value.(S), success
end

m = 1
A = (m+1)/m * Σ
Sinit = zeros(p, p)
D = A - Sinit

Σ11 = Σ[1:5, 1:5]
A11 = A[1:5, 1:5]
A12 = A[1:5, 6:end]
D22 = D[6:end, 6:end]
D12 = D[1:5, 6:end]
D21 = D[6:end, 1:5]
invD22 = inv(D22 + 0.00001I)
ub = Symmetric(A11 - D12 * invD22 * D21)

solve_group_MVR_single_block(Σ11, A11, A12, invD22, m, ub)

LoadError: MethodError: no method matching VariableRef(::AffExpr)
Closest candidates are:
  VariableRef(::Any, ::Any) at ~/.julia/packages/JuMP/puvTM/src/variables.jl:203
  VariableRef(::ConstraintRef{<:AbstractModel, <:MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex}}) at ~/.julia/packages/JuMP/puvTM/src/variables.jl:378
  VariableRef(::Model) at ~/.julia/packages/JuMP/puvTM/src/variables.jl:352
  ...

In [61]:
eigvals(S)

LoadError: UndefVarError: S not defined

In [47]:
    invZ_Yt = invD22 * A12'
    Y_invZYt = A12 * invZYt

5×5 Matrix{Float64}:
  0.310498      0.000110537   0.0488194   0.0887203   -0.0467877
  0.000110537   0.374977     -0.100284    0.0936878   -0.0477473
  0.0488194    -0.100284      0.364384   -0.0444843    0.0942238
  0.0887203     0.0936878    -0.0444843   0.358517     0.00535412
 -0.0467877    -0.0477473     0.0942238   0.00535412   0.384187

In [50]:
invZ_Yt*(A11-S-YinvZYt)*invZ_Yt'

* (affine; real)
├─ * (affine; real)
│  ├─ 45×5 Matrix{Float64}
│  └─ + (affine; real)
│     ├─ 5×5 Matrix{Float64}
│     ├─ - (affine; real)
│     │  └─ …
│     └─ 5×5 Matrix{Float64}
└─ 5×45 adjoint(::Matrix{Float64}) with eltype Float64

## Block MVR (using Convex.jl)

In [ ]:
using Convex

# function solve_SDP(Σ::AbstractMatrix)
#     svar = Variable(size(Σ, 1), Convex.Positive())
#     add_constraint!(svar, svar ≤ 1)
#     constraint = 2*Symmetric(Σ) - diagm(svar) in :SDP
#     problem = maximize(sum(svar), constraint)
#     solve!(problem, Hypatia.Optimizer; silent_solver=true)
#     s = clamp.(evaluate(svar), 0, 1) # make sure s_j ∈ (0, 1)
#     return s
# end

# this uses Convex.jl
function solve_group_MVR_single_block(
    Σ11::AbstractMatrix,
    A11::AbstractMatrix,
    A12::AbstractMatrix, 
    invD22::AbstractMatrix,
    m::Int,
    ub::AbstractMatrix; # this is upper bound, equals [A12 A13]*inv(A22-S2 A32; A23 A33-S3)*[A21; A31]
    )
    # needed constants
    invZYt = invD22 * A12'
    YinvZYt = A12 * invZYt
    
    # constraints
    p = size(Σ11, 1)
    svar = Semidefinite(p)
    add_constraint!(svar, svar ≤ 1)
    add_constraint!(svar, svar ≥ -1)
    constraint = ub - svar in :SDP
    
    # objective
    problem = minimize(
        m^2*tr(inv(S)) + tr(A11-S-YinvZYt) + tr(YinvZYt'*(A11-S-YinvZYt)*YinvZYt),
        constraint
    )

    # solve and return
    JuMP.optimize!(model)
    success = Knockoffs.check_model_solution(model)
    return JuMP.value.(S), success
end


In [18]:
p = size(Σ11, 1)
S = Semidefinite(p)
add_constraint!(S, svar ≤ 1)
add_constraint!(S, svar ≥ -1)
S

Variable
size: (5, 5)
sign: real
vexity: affine
id: 134…327

In [19]:
S.constraints

3-element Vector{Constraint}:
 sdp constraint (affine)
└─ 5×5 real variable (id: 134…327)
 <= constraint (affine)
├─ 5×5 real variable (id: 355…811)
└─ 1
 >= constraint (affine)
├─ 5×5 real variable (id: 355…811)
└─ -1

In [20]:
constraint = ub - S in :SDP

sdp constraint (affine)
└─ + (affine; real)
   ├─ 5×5 Symmetric{Float64, Matrix{Float64}}
   └─ - (affine; real)
      └─ 5×5 real variable (id: 134…327)

In [22]:
problem = minimize(
    m^2*tr(inv(S)) + tr(A-S-YinvZYt) + tr(invZYt'*(A11-S-YinvZYt)*YinvZYt),
    constraint
)

LoadError: Cannot add expressions of sizes (50, 50) and (5, 5)

In [24]:
A

50×50 Matrix{Float64}:
  2.0        -0.271149   -0.032879    …  -0.0947729    0.0801876
 -0.271149    2.0        -0.0243168      -0.0314542   -0.161222
 -0.032879   -0.0243168   2.0            -0.0182271   -0.101857
 -0.0761243  -0.0934999  -0.141387        0.316618     0.103354
 -0.020243    0.164665   -0.00873287     -0.00705244  -0.0531738
 -0.145071   -0.0814823  -0.119608    …   0.0537927   -0.200701
 -0.106396   -0.0385128  -0.0083662       0.0765058   -0.282234
  0.0704449   0.0450692   0.0910859      -0.0721822    0.265512
  0.229754    0.143721   -0.0126377      -0.0309272    0.219629
  0.0354905  -0.168119    0.115841        0.00548069  -0.0542383
  0.196919   -0.0718144  -0.0108042   …   0.0735863   -0.262046
 -0.135652    0.0582198  -0.0353113      -0.0161846   -0.00994014
 -0.174641    0.137293   -0.110705        0.010365    -0.0552382
  ⋮                                   ⋱               
 -0.124399    0.102943    0.207536        0.00364047  -0.0590465
  0.0258755  -0.041

## Use @objective with slack variables or NLobjective directly?

In [11]:
function slack_SDP_single_block(
    Σ11::AbstractMatrix,
    ub::AbstractMatrix;  # this is upper bound, equals [A12 A13]*inv(A22-S2 A32; A23 A33-S3)*[A21; A31]
    optm=Hypatia.Optimizer(verbose=false, iter_limit=100) # Any solver compatible with JuMP
    )
    # Build model via JuMP
    p = size(Σ11, 1)
    model = Model(() -> optm)
    @variable(model, -1 ≤ S[1:p, 1:p] ≤ 1, Symmetric)
    # slack variables to handle absolute value in obj 
    @variable(model, U[1:p, 1:p], Symmetric)
    for i in 1:p, j in i:p
        @constraint(model, Σ11[i, j] - S[i, j] ≤ U[i, j])
        @constraint(model, -U[i, j] ≤ Σ11[i, j] - S[i, j])
    end
    @objective(model, Min, sum(U))
    # SDP constraints
    @constraint(model, S in PSDCone())
    @constraint(model, ub - S in PSDCone())
    # solve and return
    JuMP.optimize!(model)
    return JuMP.value.(S)
end

using SCS
function NLObj_SDP_single_block(
    Σ11::AbstractMatrix,
    ub::AbstractMatrix;  # this is upper bound, equals [A12 A13]*inv(A22-S2 A32; A23 A33-S3)*[A21; A31]
    optm=SCS.Optimizer() # Any solver compatible with JuMP
    )
    # Build model via JuMP
    p = size(Σ11, 1)
    model = Model(() -> optm)
    @variable(model, -1 ≤ S[1:p, 1:p] ≤ 1, Symmetric)
    @NLobjective(model, Min, sum(abs(Σ11[i, j] - S[i, j]) for i in 1:p, j in 1:p))
    # SDP constraints
    @constraint(model, S in PSDCone())
    @constraint(model, ub - S in PSDCone())
    # solve and return
    JuMP.optimize!(model)
    return JuMP.value.(S)
end

NLObj_SDP_single_block (generic function with 1 method)

In [12]:
m = 1

# initialize with equicorrelated solution
# Sequi, γ = solve_s_group(Σ, groups, :equi)
Sequi = zeros(p, p)

# form constraints for block 1
Σ11 = Σ[1:5, 1:5]
A = (m+1)/m * Σ
D = A - Sequi
A11 = @view(A[1:5, 1:5])
D12 = @view(D[1:5, 6:end])
D22 = @view(D[6:end, 6:end])
ub = A11 - D12 * inv(D22) * D12'

# solve 
@time slack = slack_SDP_single_block(Σ11, ub)
@time nl = NLObj_SDP_single_block(Σ11, ub);

  0.209440 seconds (458.88 k allocations: 24.826 MiB, 57.65% compilation time)


LoadError: The solver does not support nonlinear problems (i.e., NLobjective and NLconstraint).

In [22]:
using JuMP
using MosekTools

model = Model(Mosek.Optimizer)

@variable(model, 2.5 ≤ z1 ≤ 5.0)
@variable(model, -1.0 <= z2 <= 1.0)
@objective(model, Min, abs(z1+5.0) + abs(z2-3.0))

LoadError: Constraints of type MathOptInterface.VariableIndex-in-MathOptInterface.GreaterThan{Float64} are not supported by the solver.

If you expected the solver to support your problem, you may have an error in your formulation. Otherwise, consider using a different solver.

The list of available solvers, along with the problem types they support, is available at https://jump.dev/JuMP.jl/stable/installation/#Supported-solvers.

Try block descent

In [6]:
@time Ssdp, _ = solve_s_group(
    Σ, groups, :sdp,
    m = 1, 
    verbose=true,
    niter=5
);

Init obj = 651.4494943754169
Iter 1 δ = 0.9536228199702621, obj = 430.76840338555894


┌ Warning: cannot step in centering direction
└ @ Hypatia.Solvers /Users/biona001/.julia/packages/Hypatia/gNjn6/src/Solvers/steppers/combined.jl:106


Iter 2 δ = 0.826901097351207, obj = 426.18848412004144


┌ Warning: cannot step in centering direction
└ @ Hypatia.Solvers /Users/biona001/.julia/packages/Hypatia/gNjn6/src/Solvers/steppers/combined.jl:106
┌ Warning: cannot step in centering direction
└ @ Hypatia.Solvers /Users/biona001/.julia/packages/Hypatia/gNjn6/src/Solvers/steppers/combined.jl:106


Iter 3 δ = 0.029548257620773677, obj = 425.975056006773
Iter 4 δ = 0.5597317692795303, obj = 419.2123948332009


┌ Warning: cannot step in centering direction
└ @ Hypatia.Solvers /Users/biona001/.julia/packages/Hypatia/gNjn6/src/Solvers/steppers/combined.jl:106
┌ Warning: cannot step in centering direction
└ @ Hypatia.Solvers /Users/biona001/.julia/packages/Hypatia/gNjn6/src/Solvers/steppers/combined.jl:106


Iter 5 δ = 0.035389868543257264, obj = 419.0889051776713
 44.680826 seconds (127.32 M allocations: 7.957 GiB, 3.62% gc time, 77.06% compilation time)


In [3]:
@time Sequi, _ = solve_s_group(
    Σ, groups, :equi,
    m = 1, 
);

  0.139828 seconds (439.08 k allocations: 24.683 MiB, 86.85% compilation time)


In [8]:
@time Ssdp_subopt, _ = solve_s_group(
    Σ, groups, :sdp_subopt,
    m = 1, 
);

  1.880804 seconds (856.86 k allocations: 91.592 MiB, 7.57% gc time, 35.69% compilation time)


In [4]:
@time Sme, _ = solve_s_group(
    Σ, groups, :maxent,
    m = 1, 
    verbose=true
);

initial obj = -1001.2975818995944
Iter 1: obj = -676.9797433696642, δ = 0.7148761215068528, t1 = 0.14, t2 = 0.04, t3 = 0.0
Iter 2: obj = -667.02018374056, δ = 0.1389593291910438, t1 = 0.15, t2 = 0.05, t3 = 0.0
Iter 3: obj = -665.1059850352791, δ = 0.021527165678117164, t1 = 0.16, t2 = 0.07, t3 = 0.0
Iter 4: obj = -664.2229660971566, δ = 0.00986453850330372, t1 = 0.17, t2 = 0.08, t3 = 0.0
  0.553342 seconds (1.08 M allocations: 58.418 MiB, 5.56% gc time, 79.26% compilation time)


In [9]:
sum(Sequi), sum(Ssdp), sum(Sme), sum(Ssdp_subopt)

(31.681698156089773, 312.2139302866235, 66.42467742735388, 223.5460638065474)

In [11]:
Ssdp

200×200 Matrix{Float64}:
 1.0       0.559985  0.551354  0.472459  …  0.0        0.0       0.0
 0.559985  1.0       0.983603  0.842856     0.0        0.0       0.0
 0.551354  0.983603  1.0       0.856051     0.0        0.0       0.0
 0.472459  0.842856  0.856051  1.0          0.0        0.0       0.0
 0.37607   0.670901  0.681403  0.795189     0.0        0.0       0.0
 0.0       0.0       0.0       0.0       …  0.0        0.0       0.0
 0.0       0.0       0.0       0.0          0.0        0.0       0.0
 0.0       0.0       0.0       0.0          0.0        0.0       0.0
 0.0       0.0       0.0       0.0          0.0        0.0       0.0
 0.0       0.0       0.0       0.0          0.0        0.0       0.0
 0.0       0.0       0.0       0.0       …  0.0        0.0       0.0
 0.0       0.0       0.0       0.0          0.0        0.0       0.0
 0.0       0.0       0.0       0.0          0.0        0.0       0.0
 ⋮                                       ⋱                       
 0.0       0

In [10]:
Ssdp_subopt

200×200 Matrix{Float64}:
 1.0       0.559985  0.551354  0.472459  …  0.0       0.0       0.0
 0.559985  1.0       0.983603  0.842856     0.0       0.0       0.0
 0.551354  0.983603  1.0       0.856051     0.0       0.0       0.0
 0.472459  0.842856  0.856051  1.0          0.0       0.0       0.0
 0.37607   0.670901  0.681403  0.795189     0.0       0.0       0.0
 0.0       0.0       0.0       0.0       …  0.0       0.0       0.0
 0.0       0.0       0.0       0.0          0.0       0.0       0.0
 0.0       0.0       0.0       0.0          0.0       0.0       0.0
 0.0       0.0       0.0       0.0          0.0       0.0       0.0
 0.0       0.0       0.0       0.0          0.0       0.0       0.0
 0.0       0.0       0.0       0.0       …  0.0       0.0       0.0
 0.0       0.0       0.0       0.0          0.0       0.0       0.0
 0.0       0.0       0.0       0.0          0.0       0.0       0.0
 ⋮                                       ⋱                      
 0.0       0.0       0.0  

In [222]:
[vec(Sequi) vec(Ssdp) vec(Sme)]

40000×3 Matrix{Float64}:
 0.0626931  1.0       0.555897
 0.0417102  0.665309  0.184368
 0.0302182  0.482002  0.0209709
 0.0288381  0.459989  0.00883674
 0.0247707  0.39511   0.00441798
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 ⋮                    
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0        0.0       0.0
 0.0130953  0.39511   0.000925487
 0.0167721  0.593875  0.00262455
 0.0186497  0.819727  0.00893611
 0.0515229  0.858956  0.169722
 0.0626931  1.0       0.32336

What if we run group knockoffs when all groups are singletons?

In [127]:
groups = collect(1:p)

# group SDP with single groups
@time Ssdp, _ = solve_s_group(
    Σ, groups, :sdp_block,
    m = 1, 
    verbose=true,
    niter=5
)

# non-grouped SDP
@time ssdp = solve_s(
    Symmetric(Σ), :sdp,
    m = 1, 
    verbose=true,
);

g = 1
A11 = [2.0;;]
size(A11) = (1, 1)


LoadError: UndefVarError: fff not defined

Here Ssdp should be diagonal matrix.

In [87]:
Ssdp

200×200 Matrix{Float64}:
 1.0  0.0  0.0  0.0       0.0      0.0       …  0.0       0.0       0.0
 0.0  1.0  0.0  0.0       0.0      0.0          0.0       0.0       0.0
 0.0  0.0  1.0  0.0       0.0      0.0          0.0       0.0       0.0
 0.0  0.0  0.0  0.995473  0.0      0.0          0.0       0.0       0.0
 0.0  0.0  0.0  0.0       0.63106  0.0          0.0       0.0       0.0
 0.0  0.0  0.0  0.0       0.0      0.554254  …  0.0       0.0       0.0
 0.0  0.0  0.0  0.0       0.0      0.0          0.0       0.0       0.0
 0.0  0.0  0.0  0.0       0.0      0.0          0.0       0.0       0.0
 0.0  0.0  0.0  0.0       0.0      0.0          0.0       0.0       0.0
 0.0  0.0  0.0  0.0       0.0      0.0          0.0       0.0       0.0
 0.0  0.0  0.0  0.0       0.0      0.0       …  0.0       0.0       0.0
 0.0  0.0  0.0  0.0       0.0      0.0          0.0       0.0       0.0
 0.0  0.0  0.0  0.0       0.0      0.0          0.0       0.0       0.0
 ⋮                                 ⋮   

In [86]:
[ssdp diag(Ssdp)]

200×2 Matrix{Float64}:
 1.0         1.0
 0.468434    1.0
 0.86833     1.0
 0.914276    0.995473
 3.36244e-8  0.63106
 0.5571      0.554254
 4.10019e-8  0.298628
 0.236487    0.265939
 0.0911048   0.198897
 0.0657967   0.186742
 0.198103    0.351992
 0.29984     0.611173
 0.694426    0.84924
 ⋮           
 0.0318133   0.047177
 0.011571    0.0522678
 0.599472    0.822529
 0.412487    0.965399
 0.819467    0.90014
 1.32504e-8  0.398157
 0.354499    0.437457
 0.403364    0.483912
 1.07897e-8  0.136476
 0.115996    0.112647
 1.02813e-8  0.181416
 0.376427    0.371388

In [89]:
eigmin(2Σ - Diagonal(ssdp))

-4.075475130804836e-9

In [91]:
eigmin(2Σ - Ssdp)

-0.3749872292309029

## How to permute things

In [224]:
S1 = reshape(1:16, 4, 4) |> Matrix
S2 = reshape(1:9, 3, 3) |> Matrix
S3 = reshape(1:4, 2, 2) |> Matrix
S = BlockDiagonal([S1, S2, S3])

9×9 BlockDiagonal{Int64, Matrix{Int64}}:
 1  5   9  13  0  0  0  0  0
 2  6  10  14  0  0  0  0  0
 3  7  11  15  0  0  0  0  0
 4  8  12  16  0  0  0  0  0
 0  0   0   0  1  4  7  0  0
 0  0   0   0  2  5  8  0  0
 0  0   0   0  3  6  9  0  0
 0  0   0   0  0  0  0  1  3
 0  0   0   0  0  0  0  2  4

In [233]:
perm = collect(1:9)
g = 2
offset = 7
cur_idx = offset + 1:offset + g
for i in 1:offset
    perm[g+i] = i
end
perm[1:g] .= cur_idx
perm

9-element Vector{Int64}:
 8
 9
 1
 2
 3
 4
 5
 6
 7

In [235]:
Spermuted = S[perm, perm]

9×9 Matrix{Int64}:
 1  3  0  0   0   0  0  0  0
 2  4  0  0   0   0  0  0  0
 0  0  1  5   9  13  0  0  0
 0  0  2  6  10  14  0  0  0
 0  0  3  7  11  15  0  0  0
 0  0  4  8  12  16  0  0  0
 0  0  0  0   0   0  1  4  7
 0  0  0  0   0   0  2  5  8
 0  0  0  0   0   0  3  6  9

In [236]:
iperm = invperm(perm)
Spermuted[iperm, iperm]

9×9 Matrix{Int64}:
 1  5   9  13  0  0  0  0  0
 2  6  10  14  0  0  0  0  0
 3  7  11  15  0  0  0  0  0
 4  8  12  16  0  0  0  0  0
 0  0   0   0  1  4  7  0  0
 0  0   0   0  2  5  8  0  0
 0  0   0   0  3  6  9  0  0
 0  0   0   0  0  0  0  1  3
 0  0   0   0  0  0  0  2  4

## Solving Convex problems

Try solving first block

In [3]:
#
# test problem
#
p = 15
group_sizes = [5 for i in 1:div(p, 5)] # each group has 5 variables
groups = vcat([i*ones(g) for (i, g) in enumerate(group_sizes)]...) |> Vector{Int}
# Σ = simulate_block_covariance(groups, 0.75, 0.25)
# Σ = Matrix(SymmetricToeplitz(0.4.^(0:(p-1)))) # true covariance matrix
# Σ = Matrix(SymmetricToeplitz((-0.4).^(0:(p-1)))) # true covariance matrix
Σ = simulate_AR1(p, a=3, b=1) # true covariance matrix

"""
    solve_full_SDP
"""
function solve_full_SDP(
    Σ11::AbstractMatrix, # correlation matrix
    ub::AbstractMatrix; # this is [A12 A13]*inv(A22-S2 A32; A23 A33-S3)*[A21; A31]
    optm=Hypatia.Optimizer(verbose=false) # Any solver compatible with JuMP
    )
    # Build model via JuMP
    p = size(Σ11, 1)
    model = Model(() -> optm)
    @variable(model, -1 ≤ S[1:p, 1:p] ≤ 1, Symmetric)
    # slack variables to handle absolute value in obj 
    @variable(model, U[1:p, 1:p], Symmetric)
    for i in 1:p, j in i:p
        @constraint(model, Σ11[i, j] - S[i, j] ≤ U[i, j])
        @constraint(model, -U[i, j] ≤ Σ11[i, j] - S[i, j])
    end
#     @constraint(model, U in PSDCone())      #### is this constraint needed????
    @objective(model, Min, sum(U))
    # SDP constraints
    @constraint(model, S in PSDCone())
    @constraint(model, ub - S in PSDCone())
    # solve and return
    JuMP.optimize!(model)
    return JuMP.value.(S), objective_value(model)
end

function solve_full_SDP_old(
    Σ11::AbstractMatrix, # correlation matrix
    ub::AbstractMatrix; # this is [A12 A13]*inv(A22-S2 A32; A23 A33-S3)*[A21; A31]
    optm=Hypatia.Optimizer(verbose=false) # Any solver compatible with JuMP
    )
    # Build model via JuMP
    p = size(Σ11, 1)
    model = Model(() -> optm)
    @variable(model, 0 ≤ S[1:p, 1:p] ≤ 1, Symmetric)
    @objective(model, Min, sum(Σ11 - S))
    # SDP constraints
    @constraint(model, S in PSDCone())
    @constraint(model, ub - S in PSDCone())
    # solve and return
    JuMP.optimize!(model)
    return JuMP.value.(S)
end

solve_full_SDP_old (generic function with 1 method)

In [4]:
m = 1

# initialize with equicorrelated solution
# Sequi, γ = solve_s_group(Σ, groups, :equi)
Sequi = zeros(p, p)

# form constraints for block 1
Σ11 = Σ[1:5, 1:5]
A = (m+1)/m * Σ
D = A - Sequi
A11 = @view(A[1:5, 1:5])
D12 = @view(D[1:5, 6:end])
D22 = @view(D[6:end, 6:end])
ub = A11 - D12 * inv(D22) * D12'

# solve 
@time S1_new, obj = solve_full_SDP(Σ11, ub)
@time S1_old = solve_full_SDP_old(Σ11, ub);

 38.529136 seconds (139.35 M allocations: 8.343 GiB, 4.92% gc time, 99.33% compilation time)
  0.162872 seconds (511.00 k allocations: 30.119 MiB, 13.71% gc time, 91.17% compilation time)


In [163]:
obj, sum(abs.(Σ11 - S1_new))

(2.696897785289176e-9, 9.016139224105046e-10)

In [160]:
eigmin(S1_new)

0.0790755108995826

In [161]:
eigmin(ub)

0.1581510007508361

Lets eyeball the result first

In [94]:
S1_new

5×5 Matrix{Float64}:
 1.0     0.4    0.16  0.064  0.0256
 0.4     1.0    0.4   0.16   0.064
 0.16    0.4    1.0   0.4    0.16
 0.064   0.16   0.4   1.0    0.4
 0.0256  0.064  0.16  0.4    1.0

In [95]:
S1_old

5×5 Matrix{Float64}:
 0.789886  0.747998  0.769968  0.644723  0.319591
 0.747998  0.962284  0.938245  0.82901   0.502877
 0.769968  0.938245  0.982537  0.854499  0.525783
 0.644723  0.82901   0.854499  0.879502  0.417846
 0.319591  0.502877  0.525783  0.417846  0.477052

In [96]:
sum(abs.(S1_new)), sum(abs.(S1_old))

(9.467199998341476, 17.192337396303046)

Check objective

In [162]:
sum(abs.(Σ11 - S1_new)), sum(abs.(Σ11 - S1_old))

(9.016139224105046e-10, 8.45111995244404)

Check constraints

In [98]:
isposdef(S1_old), isposdef(S1_new)

(true, true)

In [99]:
eigvals(ub - S1_old)

5-element Vector{Float64}:
 7.309755484523514e-9
 0.7520353697688693
 0.9080664264148712
 1.4359163255019285
 2.0506742273768

In [100]:
eigvals(ub - S1_new)

5-element Vector{Float64}:
 0.32129497088496595
 0.4766120211625212
 0.643214501447116
 1.0285108585981437
 1.7683208812336677

### Singleton groups?

In [105]:
groups[2:5] .= 2
groups

15-element Vector{Int64}:
 1
 2
 2
 2
 2
 2
 2
 2
 2
 2
 3
 3
 3
 3
 3

In [132]:
m = 1

# initialize with equicorrelated solution
Sequi, γ = solve_s_group(Σ, groups, :equi)

# form constraints for block 1
g = 1
Σ11 = @view(Σ[1, 1])
A = (m+1)/m * Σ
D = A - Sequi
Σ11 = @view(Σ[1:g, 1:g])
A11 = @view(A[1:g, 1:g])
D12 = @view(D[1:g, g + 1:end])
D21 = @view(D[g + 1:end, 1:g])
D22 = @view(D[g + 1:end, g + 1:end])
ub = Symmetric(A11 - D21' * inv(D22) * D21)

# solve 
@time S1_new, U = solve_full_SDP(Σ11, ub)
# @time S1_old = solve_full_SDP_old(Σ11, ub);

  0.066523 seconds (118.17 k allocations: 6.466 MiB, 89.63% compilation time)


In [134]:
S1_new, ub

([0.8644309427462861;;], [0.8644309426414065;;])

## Woodbury updates

Suppose we have 

\begin{align*}
    S = 
    \begin{bmatrix}
        S^{(1)} & & \\
        & S^{(2)} & \\
        & & S^{(3)}
    \end{bmatrix}
\end{align*}
And we want to udpate $S^{(1)}$

$$(A + UC)^{-1} = A^{-1} - A^{-1}U(I + VA^{-1}U)^{-1}VA^{-1}$$

In [1]:
using WoodburyMatrices

In [ ]:
A = 